大規模改修
gomagom/music-game pull request #2
Opened 2021-06-24 04:22 UTC by gomagom

- メインメニューを作り直し
- ゲーム本体を作り直し
- 曲選択画面やリザルト画面なども追加

2021-06-24 07:00 UTC, Amakuchisan requested changes
Perfect(改修後のUIすごくなってました……)

2021-06-24 07:00 UTC, Amakuchisan commented on js/game/class.js
> +        const STRING = ['Parfect!', 'Great!', 'Good!', 'Bad...'];
```suggestion
        const STRING = ['Perfect!', 'Great!', 'Good!', 'Bad...'];
```
パーフェクト……

2021-06-24 07:05 UTC, yamakenji24 requested changes
全体的な感想ですが、ゲームとしてはよくできていると思います。
前回のものから非常にバージョンアップされており、わかりやすくなっていたと思います。
ファイルのわけ方などが少し雑かなーっていう雰囲気を感じました。
１クラス１ファイル等、何の実装を行っているファイルか、わかりやすい方が望ましいです。 

[MUST]で指摘したポイントだけは、修正をお願いします。
他の部分に関してですが、現状の推奨事項やこうした方が良さそうかも？ 的なものも含まれていますので、検討をお願いします。

2021-06-24 07:05 UTC, yamakenji24 commented on js/game/game.js
> +window.onload = () => {
[MUST] window.onloadのようなDomイベントの操作は、EventListenerで制御する方が現状推奨されています。
例えば、window.onloadの場合は、`window.addEventListener('load', () => {})` 。

2021-06-24 07:05 UTC, yamakenji24 commented on js/index/script.js
> +const KEY_CONFIG = document.getElementsByClassName('key-config');
[IMO] 大文字宣言は基本的に、中の値が変わらないことを保証するためにつけるものです。
jsのオブジェクトの場合、変更できるのでどうなんだろうというのがお気持ちです。

2021-06-24 07:05 UTC, yamakenji24 commented on js/index/script.js
> +window.onbeforeunload = () => {
[IMO] 同様に、eventlistener でイベントを制御した方が適切だと思います！

2021-06-24 07:05 UTC, yamakenji24 commented on js/index/script.js
> +window.onload = () => {
[MUST] window.onloadのようなDomイベントの操作は、EventListenerで制御する方が現状推奨されています。
例えば、window.onloadの場合は、window.addEventListener('load', () => {}) 。

2021-06-24 07:05 UTC, yamakenji24 commented on js/index/script.js
> +    }
[IMO] 例外発生後に、例外発生しない前提での処理が記述されているように思うので、try catchの中で書いた方がいいように思いました。

2021-06-24 07:05 UTC, yamakenji24 commented on js/game/game.js
> +    }
[IMO] 例外発生後に、例外発生しない前提での処理が記述されているように思うので、try catchの中で書いた方がいいように思いました。

2021-06-24 07:05 UTC, yamakenji24 commented on js/game/function.js
> +    TMP.forEach((val, index) => RESULT[index] = val.split(','));    // ','の位置で分割して格納
[IMO] array.mapを使った方がコードがスッキリすると思います!
もし、可能そうであれば、splitと同時に数値型への変換も検討してみてください。
`val.split.map(Number)` みたいなのはできないかな・・？

2021-06-24 07:05 UTC, yamakenji24 commented on js/game/class.js
> +class JudgeLine {
[Q] JudgeLineが何を受け持つクラスなのか、よくわかりませんでした。

2021-06-24 07:05 UTC, yamakenji24 commented on js/game/game.js
> +};
[IMO] Scoreを管理するクラスを作ってみるのもありかなと思いました。

2021-06-24 07:05 UTC, yamakenji24 commented on js/game/function.js
> +    const INFO = document.getElementsByClassName('result-info');
[IMO] ここのInfoの変数名が、game.jsで定義されているものと同等になるので、例えばResultInfoのように、違いがわかるといいなとおもいました。

2021-06-24 07:05 UTC, yamakenji24 commented on js/game/function.js
> +    window.onbeforeunload = () => {
[IMO] 下記同様

2021-06-24 07:05 UTC, yamakenji24 commented on js/index/script.js
> +window.onbeforeunload = () => {
[Q] リロード等をしても、再プレイできるようにするための実装ですか？

2021-06-24 07:05 UTC, yamakenji24 commented on js/game/game.js
> +        console.log(ELEMENT.uploadMusicFile.files[0].name);
[NITS] `console.log` 残ったままになってる 👀

2021-06-24 07:06 UTC, yamakenji24 commented on js/game/class.js
> +        const STRING = ['Parfect!', 'Great!', 'Good!', 'Bad...'];
パーフェクト!

2021-06-29 09:11 UTC, gomagom commented on js/game/class.js
> +        const STRING = ['Parfect!', 'Great!', 'Good!', 'Bad...'];
あっ...修正しました

2021-06-29 09:19 UTC, gomagom commented on js/game/game.js
> +window.onload = () => {
一通りEventListener制御に変更しました。

2021-06-29 09:20 UTC, gomagom commented on js/index/script.js
> +window.onbeforeunload = () => {
そうです！BGMやSEのボリューム、キーコンフィグなどをローカルストレージに保存し、再びアクセスされた際に読み込むようにしてます。

2021-06-29 09:21 UTC, gomagom commented on js/index/script.js
> +window.onload = () => {
修正しました

2021-06-29 09:21 UTC, gomagom commented on js/index/script.js
> +    }
if文をtryの中に入れました！

2021-06-29 09:22 UTC, gomagom commented on js/game/game.js
> +    }
書き換えました。

2021-06-29 09:22 UTC, gomagom commented on js/game/function.js
> +    const INFO = document.getElementsByClassName('result-info');
変数名をINFO→RESULT_INFOとしました。

2021-06-29 09:23 UTC, gomagom commented on js/game/function.js
> +    window.onbeforeunload = () => {
修正しました。

2021-06-29 09:24 UTC, gomagom commented on js/game/game.js
> +        console.log(ELEMENT.uploadMusicFile.files[0].name);
ありゃ、すいません。消しました。

2021-06-29 09:34 UTC, gomagom commented on js/game/class.js
> +class JudgeLine {
canvas内の判定用ラインの座標情報などを保持し、自身を描画するって感じですかね。ノーツの座標もこれを基準に求めています。

2021-06-29 11:30 UTC, gomagom commented on js/game/function.js
> +    TMP.forEach((val, index) => RESULT[index] = val.split(','));    // ','の位置で分割して格納
array.mapで修正しました。
val.split(',').map(Number)で数値型への変換も同時にできました！

2021-06-29 12:01 UTC, gomagom commented on js/index/script.js
> +const KEY_CONFIG = document.getElementsByClassName('key-config');
配列も下のような場合小文字にしたほうがいいですか？
const BACK_LANE = [];

2021-06-29 12:45 UTC, gomagom commented on js/game/game.js
> +};
スコアを管理するGameScoreManagerを作ってみました

2021-07-01 08:59 UTC, yamakenji24 commented on js/game/game.js
> +    }
さらに付き加えると、例外発生後のエラーハンドリングがあるとなお良いかなーと思いました。
localstorageからほぼ取ってこれるように設計されているとは思いますが、取ってこれなかった時ようにトップ画面に戻る/曲を選択する...等々のハンドリングがあっても良いのかなと(なくても動きますが)

2021-07-01 09:46 UTC, yamakenji24 commented on js/game/function.js
> +    TMP.forEach((val, index) => RESULT[index] = val.split(','));    // ','の位置で分割して格納
LGTM!

2021-07-02 10:19 UTC, yamakenji24 requested changes
全体的に良くなってきていると思います!

2021-07-02 10:19 UTC, yamakenji24 commented on js/game/init.js
> +    const DATA = new Array(4);
[IMO] DATAという変数名が曖昧かなと思います。具体的な格納されているデータを表すような命名が良いかなと思います。(scoreData, musicDataなどなど)

2021-07-02 10:19 UTC, yamakenji24 commented on js/game/loop.js
> +        if (gameActive && !gameFinish) {
[Q] 全体的に、gameFinishがなくても、gameActiveだけでいけそうなのかなという雰囲気を感じるんですが、どうなんでしょうか？

2021-07-02 10:19 UTC, yamakenji24 commented on js/game/main.js
> +};
[IMO] soundに関連する処理がいくつか見られるので、クラスでまとめちゃっても良いかもと思いました。
[Q] sound.bgm.volume は見た感じ使ってなさそう...?

2021-07-02 10:19 UTC, yamakenji24 commented on js/game/main.js
> +};
[Q] ここのinfo、代入だけされてて特に他で使ってそうな場所が見当たらないのですが、将来的に使う予定というニュアンスで？

2021-07-03 16:56 UTC, gomagom commented on js/game/main.js
> +};
デバックで使ったり、画面表示用に使うかなと思っていたのですが、使わなそうなので削除しました。

2021-07-03 16:59 UTC, gomagom commented on js/game/main.js
> +};
sound関連はクラスでまとめました。sound.bgm.volumeはbgmの音量変更で使っています。loop.jsの79行目あたりですかね。

2021-07-03 17:03 UTC, gomagom commented on js/game/loop.js
> +        if (gameActive && !gameFinish) {
ポーズ画面を出すときに、gameActiveだけだとリザルト画面に移行しているかどうか分からないので、今のやり方だと必要ですね。

2021-07-03 17:05 UTC, gomagom commented on js/game/init.js
> +    const DATA = new Array(4);
譜面の管理もクラスにまとめました。

2021-07-09 08:11 UTC, yamakenji24 commented on js/game/main.js
> +};
把握しました 
sound.bgm は new Audioに紐づいているんですね

2021-07-18 09:15 UTC, merged